name: Deploy Static Site

on:
  push:
    branches:
      - main
      - stage

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      VPS_TARGET_DIR: ${{ github.ref_name == 'main' && '/var/www/aaronseo.dev' || github.ref_name == 'stage' && '/var/www/stage.aaronseo.dev' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          ref: ${{ github.ref_name }}

      - name: Deploy main
        if: github.ref_name == 'main'
        uses: appleboy/scp-action@master
        with:
          source: "./page/"
          target: "/var/www/aaronseodev"
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}

      - name: Deploy stage
        if: github.ref_name == 'stage'
        uses: appleboy/scp-action@master
        with:
          source: "./page/"
          target: "/var/www/stage.aaronseodev"
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}

      - name: Executing remote command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          port: ${{ secrets.VPS_PORT }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: ls
